server:
  port: 80
  servlet:
    context-path: /Dorm
spring:
  # 配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.99.145.57:3306/dorm_db?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: zzh
    password: 123456
    # 指定德鲁伊连接池.
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  # 扫描映射文件
  mapper-locations: mapper/*.xml
  # 配置别名
  type-aliases-package: com.example.dorm.bean
  configuration:
    # 开启驼峰映射.
    map-underscore-to-camel-case: true
logging:
  file:
    path: ./logs
  pattern:
    level: info
